version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RH
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ca1920
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025
    depends_on:
      - db
      - maildev
      - sonarqube # Ensure SonarQube starts first

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ca1920
      POSTGRES_DB: RH
    ports:
      - "5433:5432"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # Interface Web
      - "1025:1025" # SMTP

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000" # Access SonarQube at http://localhost:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: ca1920
    depends_on:
      - sonar-db

  sonar-db:
    image: postgres:latest
    container_name: sonar-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ca1920
      POSTGRES_DB: sonar
    volumes:
      - sonar-db-data:/var/lib/postgresql/data

volumes:
  sonar-db-data:
