version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/RH
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ca1920
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025
    depends_on:
      - db
      - maildev

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ca1920
      POSTGRES_DB: RH
    ports:
      - "5433:5432"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # Interface Web
      - "1025:1025" # SMTP
      -
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus config file
    depends_on:
      - app
    networks:
      - monitoring


