apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: ClusterIP
  selector:
    app: devopsprojectcicd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: maildev-service
spec:
  type: ClusterIP
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
    - protocol: TCP
      port: 1025
      targetPort: 1025
